web_form.admin:
    path: /
    defaults:
        _controller: WebFormModule:AdminWebForm:index

web_form.admin_manage:
    path: /{name}/
    defaults:
        _controller: WebFormModule:AdminWebForm:manage
#    requirements:
#        id: \d+

web_form.admin_new_messages:
    path: /{name}/new_messages/
    defaults:
        _controller: WebFormModule:AdminWebForm:manage

web_form.admin_in_progress:
    path: /{name}/in_progress/
    defaults:
        _controller: WebFormModule:AdminWebForm:manage

web_form.admin_finished:
    path: /{name}/finished/
    defaults:
        _controller: WebFormModule:AdminWebForm:manage

web_form.admin_rejected:
    path: /{name}/rejected/
    defaults:
        _controller: WebFormModule:AdminWebForm:manage

web_form.admin_fields:
    path: /{name}/fields/
    defaults:
        _controller: WebFormModule:AdminWebForm:fields

web_form.admin_field_edit:
    path: /{name}/fields/{id}/
    defaults:
        _controller: WebFormModule:AdminWebForm:fieldEdit
    requirements:
        id: \d+

web_form.admin_settings:
    path: /{name}/settings/
    defaults:
        _controller: WebFormModule:AdminWebForm:manage

