
smart_module.catalog2:
    path: /
    defaults:
        _controller: Catalog2Module:Catalog2:index

smart_module.catalog2.item:
    path: /{slug}/{itemSlug}.html
    defaults:
        _controller: Catalog2Module:Catalog2:item
    requirements:
        itemSlug: '.+'
        slug: '.+'

smart_module.catalog2.category:
    path: /{slug}
    defaults:
        _controller: Catalog2Module:Catalog2:category
    requirements:
        slug: '.+'
