# Пример конфигурирования
parameters:
    # путь для хранения данных (структура сайтов, данные модулей и т.д.)
    smart_core_cms_data_dir: %kernel.root_dir%/usr/site

cms:
    # database (db), filesystem (fs)
    storage: db
        # настройки для 'database'
        #connection: @database_connection
        # настройки для 'filesystem'
        #path: %smart_core_cms_data_dir%

knp_menu:
    twig:
        template: CMSBundle:Menu:knp_menu.html.twig

mopa_bootstrap:
    form:
        templating: false
        show_legend: false # default is true
        checkbox_label: label
        error_type: block # or inline which is default
        render_optional_text: false
        render_required_asterisk: true

security:
    role_hierarchy:
        ROLE_ROOT:        [ROLE_USER, ROLE_ADMIN, ROLE_GUEST, ROLE_SUPER_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_GUEST]
        #ROLE_USER:        [ROLE_COMMENTER]
