# Пример конфигурирования
parameters:
    # путь для хранения данных (структура сайтов, данные модулей и т.д.)
    smart_core_cms_data_dir: %kernel.root_dir%/usr/site

cms:
    # database (db), filesystem (fs)
    storage: db
        # настройки для 'database'
        #connection: @database_connection
        # настройки для 'filesystem'
        #path: %smart_core_cms_data_dir%

avalanche_imagine:
    filters:
        100-100:
            type:    thumbnail
            options: { size: [100, 100], mode: inset, quality: 100, format: jpeg }
        200-200:
            type:    thumbnail
            options: { size: [200, 200], mode: inset, quality: 100, format: jpeg }
        300-300:
            type:    thumbnail
            options: { size: [300, 300], mode: inset, quality: 100, format: jpeg }

genemu_form:
    image: ~
    file:
        swf: /assets/uploadify/uploadify.swf
        folder: /uploads

fm_elfinder:
    locale: %locale%    # defaults to current request locale
    editor: tinymce     # other choices are ckeditor, tinymce or simple
    tinymce_popup_path: "asset[bundles/stfalcontinymce/vendor/tiny_mce/tiny_mce_popup.js]"
    showhidden: false   # defaults to false
    fullscreen: true    # defaults true, applies to simple and ckeditor editors
    include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
    compression: false  # enable if you configured the uglifycss and uglifyjs2 assetic filters and want compression
    connector:
        debug: false    # defaults to false
        roots:          # at least one root must be defined
            images:
                driver: LocalFileSystem
                path: images
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                upload_deny: ['all']
                upload_max_size: 2M
            uploads:
                driver: LocalFileSystem
                path: uploads
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                upload_deny: ['all']
                upload_max_size: 50M

knp_menu:
    twig:
        template: CMSBundle:Menu:knp_menu.html.twig

knp_disqus:
    api_key: %knp_disqus.api_key%

liip_doctrine_cache:
    namespaces:
        smart_texter:
            namespace: "smart_texter_%secret%"
            type: file_system # memcache
            directory: "%kernel.cache_dir%/smart_texter"
        cms:
            namespace: "cms_%secret%"
            type: file_system
            directory: "%kernel.cache_dir%/smart_core_cms"
        smart_blog: # @todo убрать
            namespace: "smart_blog_%secret%"
            type: file_system
            directory: "%kernel.cache_dir%/smart_blog"

mopa_bootstrap:
    form:
        templating: false
        show_legend: false # default is true
        checkbox_label: label
        error_type: block # or inline which is default
        render_optional_text: false
        render_required_asterisk: true

security:
    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_GUEST ]
        ROLE_ROOT:        [ ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_GUEST ]
        #ROLE_USER:        [ROLE_COMMENTER]

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    textarea_class: 'wysiwyg'
    language: %locale%
    theme:
        advanced:
            file_browser_callback : 'elFinderBrowser'
            theme: "advanced"
            plugins: "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist"
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect"
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor"
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen"
            theme_advanced_toolbar_location: "top"
            theme_advanced_toolbar_align: "left"
            theme_advanced_statusbar_location: "bottom"
            theme_advanced_resizing: true
            theme_advanced_resizing_use_cookie: true
            theme_advanced_resize_horizontal: false
            force_br_newlines : false
            forced_root_block : ""
            convert_urls : false
            relative_urls: false
            width: "100%"
            height: 380
            content_css: "/assets/tinymce/css/content.css" # @todo настройка в формате "asset[path/to/style.css]"
        simple:
            theme: "simple"
            force_br_newlines : false
            forced_root_block : ""
            convert_urls : false
            relative_urls: false
            width: "100%"
            height: 180
            content_css: "/assets/tinymce/css/content.css" # @todo настройка в формате "asset[path/to/style.css]"

tagcache:
    driver:        %tagcache_driver% # Memcache, Memcached, File, Sqlite, Apc, Nullcache
    #debug:         %kernel.debug%
    namespace:     %secret%
    options:
        cache_dir: "%kernel.cache_dir%/smart_core_tagcache"
        hashkey:   true
        servers:
            - 'localhost:11211:10'
