parameters:
    smart_media.local.provider: SmartCore\Bundle\MediaBundle\Provider\LocalProvider

services:
    smart_media:
        class: SmartCore\Bundle\MediaBundle\Service\MediaCloudService
        arguments: [ @service_container ]
