smart_chat:
    resource: "@SmartChatBundle/Resources/config/routing.yml"
    prefix:   /

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix: /

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"

genemu_image:
    resource: "@GenemuFormBundle/Resources/config/routing/image.xml"
genemu_upload:
    resource: "@GenemuFormBundle/Resources/config/routing/upload.xml"

smart_core_cms:
    resource: "@CMSBundle/Resources/config/routing.yml"
    prefix: /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /user
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /user

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /user
