security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
         admin_login:
            anonymous: ~
            context: smart_core_cms
            pattern: ^/admin
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin/
            logout:
                path: /admin/logout
            remember_me:
                key: "%secret%"
                name: SMART_CORE_REMEMBER_ME
                lifetime: 36000
                path: /
                domain: ~
         main:
            anonymous: ~
            context: smart_core_cms
            pattern: ^/
            form_login:
                csrf_provider: form.csrf_provider
                check_path: /user/login_check
                login_path: /user/login
                default_target_path: /user/
            logout:
                path: /user/logout
            remember_me:
                key: "%secret%"
                name: SMART_CORE_REMEMBER_ME
                lifetime: 36000
                path: /
                domain: ~

    access_control:
        - { path: ^/_assistant/, roles: ROLE_ADMIN }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/efconnect, role: ROLE_ADMIN }
        - { path: ^/elfinder, role: ROLE_ADMIN }
        #- { path: ^/user, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
