bootstrap:
    version: 2.3.2
    deps: jquery
    css: { bootstrap.min.css, bootstrap-responsive.min.css }
    js: bootstrap.min.js

jquery:
    version: 1.9.1
    proirity: 1000
    js: jquery.min.js

jquery-cookie:
    deps: jquery
    version: 1.3.1
    js: jquery.cookie.js

less:
    version: 1.7.0
    js: less.min.js
