smart_module.unicat_admin:
    path: /
    defaults:
        _controller: UnicatModule:AdminUnicat:index

smart_module.unicat_configuration_admin:
    path: /configuration_{configuration}/
    defaults:
        _controller: UnicatModule:AdminUnicat:configuration

smart_module.unicat_structure_admin:
    path: /configuration_{configuration}/structure_{id}/
    defaults:
        _controller: UnicatModule:AdminUnicat:structure
    requirements:
        id: \d+

smart_module.unicat_structure_admin_with_parent_category_id:
    path: /configuration_{configuration}/structure_{id}/{parent_category_id}/
    defaults:
        _controller: UnicatModule:AdminUnicat:structure
    requirements:
        parent_category_id: \d+
        id: \d+

smart_module.unicat_structure_edit_admin:
    path: /configuration_{configuration}/structure_{id}/edit/
    defaults:
        _controller: UnicatModule:AdminUnicat:structureEdit
    requirements:
        id: \d+

smart_module.unicat_structure_create_admin:
    path: /configuration_{configuration}/structure_create/
    defaults:
        _controller: UnicatModule:AdminUnicat:structureCreate

smart_module.unicat_category_admin:
    path: /configuration_{configuration}/structure_{structure_id}/category_{id}/
    defaults:
        _controller: UnicatModule:AdminUnicat:categoryEdit
    requirements:
        id: \d+
        structure_id: \d+

smart_module.unicat_properties_group_create_admin:
    path: /configuration_{configuration}/properties_group_create/
    defaults:
        _controller: UnicatModule:AdminUnicat:propertiesGroupCreate

smart_module.unicat_properties_admin:
    path: /configuration_{configuration}/properties_group_{group_id}/
    defaults:
        _controller: UnicatModule:AdminUnicat:properties
    requirements:
        group_id: \d+

smart_module.unicat_property_admin:
    path: /configuration_{configuration}/properties_group_{group_id}/{id}/
    defaults:
        _controller: UnicatModule:AdminUnicat:property
    requirements:
        group_id: \d+
        id: \d+

smart_module.unicat_item_create_admin:
    path: /configuration_{configuration}/item_create/
    defaults:
        _controller: UnicatModule:AdminUnicat:itemCreate

smart_module.unicat_item_create_admin_in_category:
    path: /configuration_{configuration}/item_create/{default_category_id}/
    requirements:
        default_category_id: \d+
    defaults:
        _controller: UnicatModule:AdminUnicat:itemCreate

smart_module.unicat_item_edit_admin:
    path: /configuration_{configuration}/item_{id}/
    defaults:
        _controller: UnicatModule:AdminUnicat:itemEdit
    requirements:
        id: \d+
