
smart_module.unicat:
    path: /
    defaults:
        _controller: UnicatModule:Unicat:index

smart_module.unicat.item:
    path: /{slug}/{itemSlug}.html
    defaults:
        _controller: UnicatModule:Unicat:item
    requirements:
        itemSlug: '.+'
        slug: '.+'

smart_module.unicat.category:
    path: /{slug}
    defaults:
        _controller: UnicatModule:Unicat:category
    requirements:
        slug: '.+'
