
smart_module.catalog_admin:
    path: /
    defaults:
        _controller: CatalogModule:AdminCatalog:index

smart_module.catalog_repository_admin:
    path: /repository_{repository}/
    defaults:
        _controller: CatalogModule:AdminCatalog:repository

smart_module.catalog_structure_admin:
    path: /repository_{repository}/structure_{id}/
    defaults:
        _controller: CatalogModule:AdminCatalog:structure
    requirements:
        id: \d+

smart_module.catalog_structure_admin_with_parent_category_id:
    path: /repository_{repository}/structure_{id}/{parent_category_id}/
    defaults:
        _controller: CatalogModule:AdminCatalog:structure
    requirements:
        parent_category_id: \d+
        id: \d+

smart_module.catalog_structure_edit_admin:
    path: /repository_{repository}/structure_{id}/edit/
    defaults:
        _controller: CatalogModule:AdminCatalog:structureEdit
    requirements:
        id: \d+

smart_module.catalog_structure_create_admin:
    path: /repository_{repository}/structure_create/
    defaults:
        _controller: CatalogModule:AdminCatalog:structureCreate

smart_module.catalog_category_admin:
    path: /repository_{repository}/structure_{structure_id}/category_{id}/
    defaults:
        _controller: CatalogModule:AdminCatalog:categoryEdit
    requirements:
        id: \d+
        structure_id: \d+

smart_module.catalog_properties_group_create_admin:
    path: /repository_{repository}/properties_group_create/
    defaults:
        _controller: CatalogModule:AdminCatalog:propertiesGroupCreate

smart_module.catalog_properties_admin:
    path: /repository_{repository}/properties_group_{group_id}/
    defaults:
        _controller: CatalogModule:AdminCatalog:properties
    requirements:
        group_id: \d+

smart_module.catalog_property_admin:
    path: /repository_{repository}/properties_group_{group_id}/{id}/
    defaults:
        _controller: CatalogModule:AdminCatalog:property
    requirements:
        group_id: \d+
        id: \d+

smart_module.catalog_item_create_admin:
    path: /repository_{repository}/item_create/
    defaults:
        _controller: CatalogModule:AdminCatalog:itemCreate

smart_module.catalog_item_create_admin_in_category:
    path: /repository_{repository}/item_create/{default_category_id}/
    requirements:
        default_category_id: \d+
    defaults:
        _controller: CatalogModule:AdminCatalog:itemCreate

smart_module.catalog_item_edit_admin:
    path: /repository_{repository}/item_{id}/
    defaults:
        _controller: CatalogModule:AdminCatalog:itemEdit
    requirements:
        id: \d+
