
smart_module.catalog:
    path: /
    defaults:
        _controller: CatalogModule:Catalog:index

smart_module.catalog.item:
    path: /{slug}.html
    defaults:
        _controller: CatalogModule:Catalog:item
    requirements:
        slug: '.+'

smart_module.catalog.category:
    path: /{slug}
    defaults:
        _controller: CatalogModule:Catalog:category
    requirements:
        slug: '.+'
