smart_module.shop.index:
    path: /
    defaults:
        _controller: ShopModuleBundle:Shop:index

smart_module.shop.checkout:
    path: /checkout/
    defaults:
        _controller: ShopModuleBundle:Shop:checkout

smart_module.shop.orders.all:
    path: /all/
    defaults:
        _controller: ShopModuleBundle:Shop:ordersAll

smart_module.shop.orders.active:
    path: /active/
    defaults:
        _controller: ShopModuleBundle:Shop:ordersActive

smart_module.shop.orders.completed:
    path: /completed/
    defaults:
        _controller: ShopModuleBundle:Shop:ordersCompleted

smart_module.shop.orders.canceled:
    path: /cancelled/
    defaults:
        _controller: ShopModuleBundle:Shop:ordersCancelled
