smart_module.shop.admin:
    path: /
    defaults:
        _controller: ShopModuleBundle:AdminShop:index

smart_module.shop.admin.baskets:
    path: /baskets/
    defaults:
        _controller: ShopModuleBundle:AdminShop:baskets

smart_module.shop.admin.basket.show:
    path: /baskets/{id}/
    defaults:
        _controller: ShopModuleBundle:AdminShop:basket
    requirements:
        id: \d+

smart_module.shop.admin.orders:
    path: /orders/
    defaults:
        _controller: ShopModuleBundle:AdminShop:orders

smart_module.shop.admin.order.show:
    path: /orders/{id}/
    defaults:
        _controller: ShopModuleBundle:AdminShop:order
    requirements:
        id: \d+

smart_module.shop.admin.orders.all:
    path: /orders/all/
    defaults:
        _controller: ShopModuleBundle:AdminShop:ordersAll

smart_module.shop.admin.orders.active:
    path: /orders/active/
    defaults:
        _controller: ShopModuleBundle:AdminShop:ordersActive

smart_module.shop.admin.orders.completed:
    path: /orders/completed/
    defaults:
        _controller: ShopModuleBundle:AdminShop:ordersCompleted

smart_module.shop.admin.orders.cancelled:
    path: /orders/cancelled/
    defaults:
        _controller: ShopModuleBundle:AdminShop:ordersCancelled

smart_module.shop.admin.orders.shipping:
    path: /orders/shipping/
    defaults:
        _controller: ShopModuleBundle:AdminShop:ordersShipping

# ------------------------------------------------------
smart_module.shop.admin.settings:
    path: /settings/
    defaults:
        _controller: ShopModuleBundle:AdminShop:settings

smart_module.shop.admin.payment:
    path: /payment/
    defaults:
        _controller: ShopModuleBundle:AdminShop:index

smart_module.shop.admin.shipping:
    path: /shipping/
    defaults:
        _controller: ShopModuleBundle:AdminShop:shipping

smart_module.shop.admin.shipping.active:
    path: /shipping/active/
    defaults:
        _controller: ShopModuleBundle:AdminShop:shippingActive

smart_module.shop.admin.shipping.finished:
    path: /shipping/finished/
    defaults:
        _controller: ShopModuleBundle:AdminShop:shippingFinished

smart_module.shop.admin.shipping.settings:
    path: /shipping/settings/
    defaults:
        _controller: ShopModuleBundle:AdminShop:shippingSettings
