
smart_module.news:
    path: /
    defaults:
        _controller: NewsModule:News:index

smart_module.news.page:
    path: /page_{page}/
    defaults:
        _controller: NewsModule:News:index
    requirements:
        page: \d+

smart_module.news.item:
    path: /{slug}.html
    defaults:
        _controller: NewsModule:News:item
    requirements:
        slug: '.+'
