parameters:
    user_class: SandboxSiteBundle\Entity\User
    #admin_path: control_panel

liip_imagine:
    filter_sets:
        demo_site_thumb:
            format: jpeg
            jpeg_quality: 100
            quality: 100
            filters:
                thumbnail: { size: [207, 177], mode: inset }
