parameters:
    #admin_path: control_panel

doctrine:
    orm:
        resolve_target_entities:
            FOS\UserBundle\Model\UserInterface: SandboxSiteBundle\Entity\User

fos_user:
    user_class: SandboxSiteBundle\Entity\User

liip_imagine:
    filter_sets:
        demo_site_thumb:
            format: jpeg
            jpeg_quality: 100
            quality: 100
            filters:
                thumbnail: { size: [207, 177], mode: inset }
